\section{Conclusion}
In this paper, we have described a flexible infrastructure for in situ triggers inside of Ascent.
%
\fix{Trigger implementations with traditional visualization tools must be written outside of the tool and have to manually implement actions.}
%
Our system treats triggers as first-class citizens, providing abstractions that separate inspection routines from VAS actions.
%
With a set of re-usable and interchangeable components, we hope to lower the barrier for trigger use and development.