\section{Conclusion}
In this paper, we have described a flexible infrastructure for in situ triggers inside of Ascent.
%
Trigger implementations with traditional visualization tools must be written outside of the tool and have to manually implement actions.
%
Our work directly integrates trigger capability into an in situ visualization and analysis infrastructure.
%
The trigger system uses modular components that provides different options for VAS actions, comparisons, and reduction methods (if needed).
%
For trigger developers, we provide re-usable and interchangeable components that lowers the barrier for trigger development.
%
We also demonstrated how different categories of triggers can be used to identify features of interest (e.g., threshold), filter out un-needed data (e.g., maximum radial distance). and highlight simulation performance bottlenecks (e.g., simulation state).

For future work, we intend to continue to develop the in situ trigger infrastructure and provide additional reduction and summarization building blocks.
%
Additionally, we would like to explore more dynamic trigger workflows where trigger can modify the input actions.
 


